### PR TITLE
Migrate PluginV2 to PluginV3

### PR DESCRIPTION
**Pull request by takeokunn**
`Phan\PluginV3` is available, so this pull request migrate PluginV2 to PluginV3.

Thans!

### CODE REVIEW

**Comment by bobvandevijver** [comment]
Hi! PluginV3 is not available in Phan v1, but we still want to support that version for now. So I wont be merging this now, as Phan v2 doesn't require the use of PluginV3 yet. Once Phan v3 arrives (which will probably drop the PluginV2), I will revisit this, but don't forget to notify me if I forget!

**Comment by igoooor** [comment]
Any plan to support V3 as support for V2 is being dropped now by phan/phan?

**Comment by bobvandevijver** [comment]
@igoooor Good question, but simple answer: Lets do it! 😃 I will see if I can get this merged.

**Comment by bobvandevijver** [comment]
Always nice to see that somehow your Travis CI integration broke 😞 

Anyways, LGTM, thanks @takeokunn for your contribution!

**Comment by bobvandevijver** [comment]
@igoooor Released as v3.0.0! Please let us know if you experience any issues!

**Comment by igoooor** [comment]
Great it works! Thanks

**Pull request merged**
